//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS411_Wrestling_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Player
    {
        public Home_Player()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int Home_Player_ID { get; set; }
        public int School_ID { get; set; }
        public string Weight_Class { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<Match> Matches { get; set; }
    }
}
