//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS411_Wrestling_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Match_ID { get; set; }
        public int Home_Player_ID { get; set; }
        public int Away_Player_ID { get; set; }
        public System.TimeSpan Match_Time { get; set; }
        public Nullable<System.TimeSpan> Home_Blood_Time { get; set; }
        public Nullable<System.TimeSpan> Away_Blood_Time { get; set; }
        public Nullable<System.TimeSpan> Home_Injury_Time { get; set; }
        public Nullable<System.TimeSpan> Away_Injury_Time { get; set; }
        public Nullable<int> Home_Points { get; set; }
        public Nullable<int> Away_Points { get; set; }
        public int Winner { get; set; }
    
        public virtual Away_Player Away_Player { get; set; }
        public virtual Home_Player Home_Player { get; set; }
    }
}
